language: cpp
compiler:
- gcc
os:
- linux
sudo: required
dist: trusty
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-5
    - g++-5
    - libcurl4-openssl-dev
    - libev-dev
    - libsqlite-dev
    - libmysqlclient-dev 
env: COMPILER=g++-5
script:
- cd chronos
- mkdir build
- cd build
- cmake .. && make
